# Generated by Django 2.2.17 on 2021-03-14 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.CharField(max_length=50)),
                ('To', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(blank=True, max_length=254)),
                ('Amount', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Qualities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age_group', models.CharField(max_length=30)),
                ('Region', models.CharField(blank=True, max_length=255)),
                ('Purpose', models.CharField(blank=True, max_length=50)),
                ('Gender', models.CharField(blank=True, max_length=20)),
                ('one', models.CharField(blank=True, max_length=20)),
                ('two', models.CharField(blank=True, max_length=20)),
                ('three', models.CharField(blank=True, max_length=20)),
                ('four', models.CharField(blank=True, max_length=20)),
                ('five', models.CharField(blank=True, max_length=20)),
                ('six', models.CharField(blank=True, max_length=20)),
                ('seven', models.CharField(blank=True, max_length=20)),
                ('eight', models.CharField(blank=True, max_length=20)),
                ('nine', models.CharField(blank=True, max_length=20)),
                ('ten', models.CharField(blank=True, max_length=20)),
                ('eleven', models.CharField(blank=True, max_length=20)),
                ('twelve', models.CharField(blank=True, max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Qualities',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('First_name', models.CharField(max_length=80)),
                ('Last_name', models.CharField(max_length=80)),
                ('Date_of_Birth', models.DateField(blank=True, null=True)),
                ('Country', models.CharField(max_length=255)),
                ('Region', models.CharField(max_length=255)),
                ('Phone', models.IntegerField(blank=True, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254)),
                ('Gender', models.CharField(max_length=40)),
                ('Description', models.TextField(max_length=4000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('other', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ematchapp.Qualities')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Messaging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.IntegerField(blank=True, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=255)),
                ('detail', models.ManyToManyField(to='ematchapp.MessageDetail')),
            ],
        ),
    ]
