# Generated by Django 2.2.17 on 2021-03-14 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ematchapp', '0003_profile_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='other',
        ),
    ]
