# Generated by Django 2.2.17 on 2021-03-14 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ematchapp', '0004_remove_profile_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='other',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ematchapp.Qualities'),
        ),
    ]
