# Generated by Django 2.2.17 on 2021-03-20 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ematchapp', '0005_profile_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagedetail',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
