# Generated by Django 2.2.17 on 2021-05-09 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ematchapp', '0008_auto_20210505_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='other',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ematchapp.Qualities'),
        ),
    ]
