# Generated by Django 2.2.17 on 2021-05-10 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ematchapp', '0009_auto_20210509_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='other',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ematchapp.Qualities'),
        ),
    ]
