# Generated by Django 2.2.17 on 2021-05-26 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ematchapp', '0010_auto_20210510_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualities',
            name='check1',
        ),
        migrations.RemoveField(
            model_name='qualities',
            name='check10',
        ),
        migrations.RemoveField(
            model_name='qualities',
            name='check11',
        ),
        migrations.RemoveField(
            model_name='qualities',
            name='check12',
        ),
        migrations.RemoveField(
            model_name='qualities',
            name='check13',
        ),
        migrations.RemoveField(
            model_name='qualities',
            name='check14',
        ),
        migrations.RemoveField(
            model_name='qualities',
            name='check15',
        ),
        migrations.RemoveField(
            model_name='qualities',
            name='check16',
        ),
        migrations.RemoveField(
            model_name='qualities',
            name='check17',
        ),
        migrations.RemoveField(
            model_name='qualities',
            name='check18',
        ),
        migrations.RemoveField(
            model_name='qualities',
            name='check19',
        ),
        migrations.RemoveField(
            model_name='qualities',
            name='check2',
        ),
        migrations.RemoveField(
            model_name='qualities',
            name='check20',
        ),
        migrations.RemoveField(
            model_name='qualities',
            name='check21',
        ),
        migrations.RemoveField(
            model_name='qualities',
            name='check22',
        ),
        migrations.RemoveField(
            model_name='qualities',
            name='check23',
        ),
        migrations.RemoveField(
            model_name='qualities',
            name='check24',
        ),
        migrations.RemoveField(
            model_name='qualities',
            name='check25',
        ),
        migrations.RemoveField(
            model_name='qualities',
            name='check3',
        ),
        migrations.RemoveField(
            model_name='qualities',
            name='check5',
        ),
        migrations.RemoveField(
            model_name='qualities',
            name='check6',
        ),
        migrations.RemoveField(
            model_name='qualities',
            name='check7',
        ),
        migrations.RemoveField(
            model_name='qualities',
            name='check8',
        ),
        migrations.RemoveField(
            model_name='qualities',
            name='check9',
        ),
    ]
