# Generated by Django 2.2.17 on 2021-05-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ematchapp', '0011_auto_20210526_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Status',
            field=models.CharField(default='Single', max_length=80),
        ),
    ]
