# Generated by Django 2.2.17 on 2021-05-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ematchapp', '0013_auto_20210529_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
