# Generated by Django 2.2.17 on 2021-05-30 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ematchapp', '0014_profile_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cover',
        ),
    ]
