# Generated by Django 2.2.17 on 2021-06-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ematchapp', '0016_auto_20210603_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Ethnicity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
