# Generated by Django 2.2.17 on 2021-06-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ematchapp', '0017_auto_20210603_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Body_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Eye_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Hair_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Height',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Weight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
