# Generated by Django 2.2.17 on 2021-06-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ematchapp', '0018_auto_20210603_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Answer_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Answer_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Recovery_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Recovery_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
