# Generated by Django 2.2.17 on 2021-06-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ematchapp', '0019_auto_20210604_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Question_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Question_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Answer_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Answer_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
