# Generated by Django 2.2.17 on 2021-06-05 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ematchapp', '0021_auto_20210605_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='Name',
        ),
        migrations.AddField(
            model_name='status',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
