# Generated by Django 2.2.17 on 2021-06-06 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ematchapp', '0022_auto_20210605_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusimage',
            name='stats',
        ),
        migrations.AddField(
            model_name='status',
            name='stats',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ematchapp.StatusImage'),
        ),
    ]
