# Generated by Django 2.2.17 on 2021-06-06 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ematchapp', '0023_auto_20210606_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
