# Generated by Django 2.2.17 on 2021-06-06 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ematchapp', '0024_auto_20210606_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
