# Generated by Django 2.2.17 on 2021-06-07 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ematchapp', '0026_status_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
