# Generated by Django 2.2.17 on 2021-06-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ematchapp', '0027_status_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='stats',
        ),
        migrations.AddField(
            model_name='status',
            name='stats',
            field=models.ManyToManyField(to='ematchapp.StatusImage'),
        ),
    ]
